/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class Complejo(
    private var real: Double=0.0,
    private var imag: Double=0.0) {

    fun inicializar(real:Double,imag:Double){
        this.real=real
        this.imag=imag
    }
    fun mostrar(){
        println(this.toString())
    }
    override fun toString():String{
        return "(${real},${imag})"
    }
    fun sumar(otro: Complejo): Complejo {
        return Complejo(
            real + otro.real,
            imag + otro.imag
        )
    }
    fun restar(otro: Complejo): Complejo {
        return Complejo(
            real - otro.real,
            imag - otro.imag
        )
    }
    fun multiplicar (otro: Complejo): Complejo {
        val nuevoReal = real * otro.real - imag * otro.imag
        val nuevoImag = real * otro.imag + imag * otro.real
        return Complejo(nuevoReal, nuevoImag)
    }
    fun dividir (otro: Complejo): Complejo {
        val nuevoReal = real / otro.real - imag / otro.imag
        val nuevoImag = real / otro.imag + imag / otro.real
        return Complejo(nuevoReal, nuevoImag)
    }
}

fun main() {
    var complejo: Complejo
    complejo= Complejo()
    complejo.inicializar(3.0,4.0)
    println("mi número complejo es ${complejo.toString()}")
    var c2:Complejo= Complejo(1.0,2.0)
    var c3:Complejo
    c3=complejo.sumar(c2)
    c3.mostrar()
    var c4:Complejo
    c4=complejo.restar(c2)
    c4.mostrar()
    var c5: Complejo 
    c5 = complejo.multiplicar(c2)
    c5.mostrar()
    var c6: Complejo 
    c6 = complejo.dividir(c2)
    c6.mostrar()


}

/*
//Trabajo practico 2026 - Ejercicio 1 - Clase Complejo (PROFE)
//class Complejo {
    private var real: Int = 0
    private var imaginario: Int = 0
    fun inicializar ( real: Int, imaginario: Int) {
        this.real = real
        this.imaginario = imaginario
    }
    fun toString(): String {
        return "(${this.real}, ${this.imaginario})"
    }
//    fun mostrar(){
//        println("(${this.real}, ${this.imaginario})") //en este caso si ponemos this.real o real solo va a ser lo mismo
//    }
}

fun main() {
    var complejo: Complejo
    complejo = Complejo()
    complejo.inicializar(3, 4)
//    complejo.mostrar()
    println("Mi complejo: ${complejo.toString()}")
}

*Codigo ROMANO
package org.example

class Complejo {  
    private var real: Int = 3
    private var  imaginario : Int = 4
    fun ponerValor(real: Int, imaginario: Int){
        this.real = real
        this.imaginario = imaginario
    }
    fun obtenervalor_real(): Int {
        return real
    }
    fun obtenervalor_imaginario(): Int {
        return imaginario
    }
    fun mostrar(): String{
        return "($real, $imaginario)"
    }
    fun sumar(otro: Complejo): Complejo {
        return Complejo(
            real + otro.real,
            imaginario + otro.imaginario
        )
    }
}

fun main() {
    val app: Complejo  
    var c3: Complejo = Complejo()
    app = Complejo()
    println (app.obtenervalor_real())
    println (app.obtenervalor_imaginario())
    println (app.mostrar())
    println (app.suma())
}
*/ 