/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class Complejo {  
    private var real: Int = 3
    private var  imaginario : Int = 4
    fun ponerValor(real: Int, imaginario: Int){
        this.real = real
        this.imaginario = imaginario
    }
    fun obtenervalor_real(): Int {
        return real
    }
    fun obtenervalor_imaginario(): Int {
        return imaginario
    }
    fun mostrar(): String{
        return "($real, $imaginario)"
    }
    fun suma(): Int{
        return (real + imaginario)
    }
}

fun main() {
    val app: Complejo 
    app = Complejo()
    println (app.obtenervalor_real())
    println (app.obtenervalor_imaginario())
    println (app.mostrar())
    println (app.suma())
}

/*
//Trabajo practico 2026 - Ejercicio 1 - Clase Complejo (PROFE)
//class Complejo {
    private var real: Int = 0
    private var imaginario: Int = 0
    fun inicializar ( real: Int, imaginario: Int) {
        this.real = real
        this.imaginario = imaginario
    }
    fun toString(): String {
        return "(${this.real}, ${this.imaginario})"
    }
//    fun mostrar(){
//        println("(${this.real}, ${this.imaginario})") //en este caso si ponemos this.real o real solo va a ser lo mismo
//    }
}

fun main() {
    var complejo: Complejo
    complejo = Complejo()
    complejo.inicializar(3, 4)
//    complejo.mostrar()
    println("Mi complejo: ${complejo.toString()}")
}
*/